# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - curl -sSL https://install.python-poetry.org | python3 -
    post_install:
      - export PATH="$HOME/.local/bin:$PATH" && poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .