# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin:$PATH" && poetry config virtualenvs.create false
    - export PATH="$HOME/.local/bin:$PATH" && poetry install --with docs
    - export PATH="$HOME/.local/bin:$PATH" && poetry run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html